interface question {
    [key: string]: string,
}
interface colorScore {
    [key: string]: number
}
export const colors: colorScore = {
    "vermelho": 0,
    "ciano": 0,
    "rosa": 0,
    "verde": 0,
    "roxo": 0,
    "amarelo": 0,
    "azul": 0,
    "laranja": 0
}
export const questions: question = {
    poder: "vermelho",
    paz: "ciano",
    ternura: "rosa",
    harmonia: "azul",
    coragem: "vermelho",
    misterio: "roxo",
    "excitação": "vermelho",
    serenidade: "azul",
    ingenuidade: "rosa",
    segurança: "ciano",
    elevação: "rosa",
    recomeço: "verde",
    "paixão": "vermelho",
    romantismo: "rosa",
    ingenuidade2: "rosa",
    conciencia: "roxo",
    riqueza: "roxo",
    sabedoria: "azul",
    ingenuidade3: "rosa",
    clareza: "amarelo",
    energia: "vermelho",
    alegria: "laranja",
    alegria2: "rosa",
    felicidade: "laranja",
    juventude: "vermelho",
    crescimento: "verde",
    paz2: "roxo",
    calma: "ciano",
    mudanças: "roxo",
    esperança: "verde",
    misterio2: "roxo",
    clareza2: "amarelo",
    imaginação: "roxo",
    clareza3: "laranja",
    compaixão: "azul",
    frio: "ciano",
    coragem2: "vermelho",
    otimismo: "amarelo",
    relaxamento2: "azul",
    crescimento2: "verde",
    calma2: "azul",
    energia2: "amarelo",
    serenidade2: "azul",
    alegria3: "laranja",
    tecnologia: "ciano",
    natureza: "verde",
    paz3: "ciano",
    energia3: "amarelo",
    calma3: "ciano",
    alegria4: "laranja",
    prosperidade: "verde",
    esperança2: "amarelo",
    harmonia2: "verde",
    exuberancia: "laranja",
    foco: "amarelo",
    "facinação": "laranja"
} 
